import axios from "axios";
import { API_CONFIG } from "../config/apiConfig";

const assessmentAxiosInstance = axios.create({
  baseURL: API_CONFIG.ASSESSMENT_SERVICE,

  headers: {
    "Content-Type": "application/json",
  },
});

/*
 * Attach the same JWT generated by Auth Service.
 *
 * Later we will configure Assessment Service
 * to validate this JWT.
 */
assessmentAxiosInstance.interceptors.request.use(
  (config) => {

    const token = localStorage.getItem("token");

    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }

    return config;
  },

  (error) => {
    return Promise.reject(error);
  }
);

export default assessmentAxiosInstance;