# 1. Server Port Configuration
# Sets the port for this microservice to avoid port conflicts with other services
server.port=8083

# 2. MongoDB Cloud (Atlas) Connection Configuration
# Paste your MongoDB Atlas URI here, replacing the password and adding your database name
spring.data.mongodb.uri=mongodb+srv://mohitchourasiacmfeb26_db_user:Mohit%4099@cluster0.dtg8jz3.mongodb.net/ai_proctoring_db?retryWrites=true&w=majority
# 3. MySQL Database Configuration (Optional: for relational data like coding submissions)
spring.datasource.url=jdbc:mysql://localhost:3306/sandbox_db
spring.datasource.username=root
spring.datasource.password=Mohit27##
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. Judge0 API Configuration (Used for compiling and executing code submissions)
judge0.api.host=https://judge0-ce.p.rapidapi.com
judge0.api.key=your_rapidapi_or_judge0_key

# 5. LLM / Gemini API Configuration (Used for AI feedback and proctoring log analysis)
gemini.api.key=AQ.Ab8RN6K4kagEHsQIp9hGqyq6ZcbXZYv0YNUQZng42xEDf7Hr1w

#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=AQ.Ab8RN6L_fpsxbey1pLAWZ9UOuPdwdEv8bteAVYIsvePgNsDFlA