# Active Profile Switcher (dev-msaxena OR dev-mohit)
spring.profiles.active=dev-msaxena

# Common Multipart Limits for Both Environments
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB